export * from './Optimizations';
export * from './SocialMedia';
export * from './Usability';
export * from './DataStructure';
export * from './Marketing';
export * from './Technologies';
export * from './WebsiteReport';
export * from './Footer';
export * from './AuditTable';